pipelineid: npm_autodiscovery
automerge: false

scm:
  enabled: true
  user: updatecli-bot
  email: updatecli-bot@updatecli.io
  owner: updatecli
  repository: updatecli
  #token: "xxx"
  username: "updatecli-bot"
  branch: main

npm:
  spec:
