name : 'deps: bump Updatecli GH action'
pipelineid: '{{ .pipelineid }}'
version: v0.103.0

sources:
    updatecli:
        name: "Get latest Updatecli version"
        kind: "githubrelease"
        spec:
            owner: "updatecli"
            repository: "updatecli-action"
            token: '{{ default ( env .github.env_token ) .github.token }}'
            username: '{{ default ( env .github.env_username ) .github.username }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'

targets:
    githubaction:
        name: 'deps: update Updatecli used by Github Action to {{ source "updatecli" }}'
        kind: yaml
        disablesourceinput: true
        spec:
            engine: yamlpath 
            key: '$.jobs.*.steps[?(@.uses =~ /^updatecli\/updatecli-action/)].uses'
            value: 'updatecli/updatecli-action@{{ source "updatecli" }}'
            files:
             - '.github/workflows/*'
            searchpattern: true
# {{ if .scm.enabled }}
        scmid: default
# {{ end }}

