_extends: policies:.github/release-drafter.yml
name-template: "kyverno-dsl-policy/v$RESOLVED_VERSION"
tag-template: "kyverno-dsl-policy/v$RESOLVED_VERSION"
tag-prefix: kyverno-dsl-policy/v
include-paths:
  - "policies/kyverno-dsl-policy/"
