_extends: policies:.github/release-drafter.yml
name-template: "volumeMounts-policy/v$RESOLVED_VERSION"
tag-template: "volumeMounts-policy/v$RESOLVED_VERSION"
tag-prefix: volumeMounts-policy/v
include-paths:
  - "policies/volumeMounts-policy/"
