_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "capabilities-psp-policy/v$RESOLVED_VERSION"
tag-template: "capabilities-psp-policy/v$RESOLVED_VERSION"
tag-prefix: capabilities-psp-policy/v
include-paths:
  - "policies/capabilities-psp-policy/"
