_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "priority-class-policy/v$RESOLVED_VERSION"
tag-template: "priority-class-policy/v$RESOLVED_VERSION"
tag-prefix: priority-class-policy/v
include-paths:
  - "policies/priority-class-policy/"
