_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "flexvolume-drivers-psp-policy/v$RESOLVED_VERSION"
tag-template: "flexvolume-drivers-psp-policy/v$RESOLVED_VERSION"
tag-prefix: flexvolume-drivers-psp-policy/v
include-paths:
  - "policies/flexvolume-drivers-psp-policy/"
