_extends: policies:.github/release-drafter.yml
name-template: "high-risk-service-account-policy/v$RESOLVED_VERSION"
tag-template: "high-risk-service-account-policy/v$RESOLVED_VERSION"
tag-prefix: high-risk-service-account-policy/v
include-paths:
  - "policies/high-risk-service-account-policy/"
