_extends: policies:release-drafter.yml
name-template: "runtime-enforcer-policy/v$RESOLVED_VERSION"
tag-template: "runtime-enforcer-policy/v$RESOLVED_VERSION"
tag-prefix: runtime-enforcer-policy/v
include-paths:
  - "policies/runtime-enforcer-policy/"
