_extends: policies:.github/release-drafter.yml
name-template: "sleeping-policy/v$RESOLVED_VERSION"
tag-template: "sleeping-policy/v$RESOLVED_VERSION"
tag-prefix: sleeping-policy/v
include-paths:
  - "policies/sleeping-policy/"
