_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "hostpaths-psp-policy/v$RESOLVED_VERSION"
tag-template: "hostpaths-psp-policy/v$RESOLVED_VERSION"
tag-prefix: hostpaths-psp-policy/v
include-paths:
  - "policies/hostpaths-psp-policy/"
