_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "annotations-policy/v$RESOLVED_VERSION"
tag-template: "annotations-policy/v$RESOLVED_VERSION"
tag-prefix: annotations-policy/v
include-paths:
  - "policies/annotations-policy/"
