_extends: policies:.github/release-drafter.yml
name-template: "go-wasi-context-aware-test-policy/v$RESOLVED_VERSION"
tag-template: "go-wasi-context-aware-test-policy/v$RESOLVED_VERSION"
tag-prefix: go-wasi-context-aware-test-policy/v
include-paths:
  - "policies/go-wasi-context-aware-test-policy/"
