_extends: policies:.github/release-drafter.yml
name-template: "probes-policy/v$RESOLVED_VERSION"
tag-template: "probes-policy/v$RESOLVED_VERSION"
tag-prefix: probes-policy/v
include-paths:
  - "policies/probes-policy/"
