_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "raw-mutation-policy/v$RESOLVED_VERSION"
tag-template: "raw-mutation-policy/v$RESOLVED_VERSION"
tag-prefix: raw-mutation-policy/v
include-paths:
  - "policies/raw-mutation-policy/"
