_extends: policies:.github/release-drafter.yml
name-template: "share-pid-namespace-policy/v$RESOLVED_VERSION"
tag-template: "share-pid-namespace-policy/v$RESOLVED_VERSION"
tag-prefix: share-pid-namespace-policy/v
include-paths:
  - "policies/share-pid-namespace-policy/"
