_extends: policies:.github/release-drafter.yml
name-template: "psa-label-enforcer-policy/v$RESOLVED_VERSION"
tag-template: "psa-label-enforcer-policy/v$RESOLVED_VERSION"
tag-prefix: psa-label-enforcer-policy/v
include-paths:
  - "policies/psa-label-enforcer-policy/"
