_extends: policies:.github/release-drafter.yml
name-template: "allowed-proc-mount-types-psp-policy/v$RESOLVED_VERSION"
tag-template: "allowed-proc-mount-types-psp-policy/v$RESOLVED_VERSION"
tag-prefix: allowed-proc-mount-types-psp-policy/v
include-paths:
  - "policies/allowed-proc-mount-types-psp-policy/"
