_extends: policies:.github/release-drafter.yml
name-template: "safe-labels-policy/v$RESOLVED_VERSION"
tag-template: "safe-labels-policy/v$RESOLVED_VERSION"
tag-prefix: safe-labels-policy/v
include-paths:
  - "policies/safe-labels-policy/"
