_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "sysctl-psp-policy/v$RESOLVED_VERSION"
tag-template: "sysctl-psp-policy/v$RESOLVED_VERSION"
tag-prefix: sysctl-psp-policy/v
include-paths:
  - "policies/sysctl-psp-policy/"
