_extends: policies:.github/release-drafter.yml
name-template: "apparmor-psp-policy/v$RESOLVED_VERSION"
tag-template: "apparmor-psp-policy/v$RESOLVED_VERSION"
tag-prefix: apparmor-psp-policy/v
include-paths:
  - "policies/apparmor-psp-policy/"
