_extends: policies:.github/release-drafter.yml
name-template: "volumes-psp-policy/v$RESOLVED_VERSION"
tag-template: "volumes-psp-policy/v$RESOLVED_VERSION"
tag-prefix: volumes-psp-policy/v
include-paths:
  - "policies/volumes-psp-policy/"
