_extends: policies:.github/release-drafter.yml
name-template: "do-not-expose-admission-controller-webhook-services-policy/v$RESOLVED_VERSION"
tag-template: "do-not-expose-admission-controller-webhook-services-policy/v$RESOLVED_VERSION"
tag-prefix: do-not-expose-admission-controller-webhook-services-policy/v
include-paths:
  - "policies/do-not-expose-admission-controller-webhook-services-policy/"
