_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "image-cve-policy/v$RESOLVED_VERSION"
tag-template: "image-cve-policy/v$RESOLVED_VERSION"
tag-prefix: image-cve-policy/v
include-paths:
  - "policies/image-cve-policy/"
