_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "env-variable-secrets-scanner-policy/v$RESOLVED_VERSION"
tag-template: "env-variable-secrets-scanner-policy/v$RESOLVED_VERSION"
tag-prefix: env-variable-secrets-scanner-policy/v
include-paths:
  - "policies/env-variable-secrets-scanner-policy/"
