_extends: policies:.github/release-drafter.yml
name-template: "pod-ndots-policy/v$RESOLVED_VERSION"
tag-template: "pod-ndots-policy/v$RESOLVED_VERSION"
tag-prefix: pod-ndots-policy/v
include-paths:
  - "policies/pod-ndots-policy/"
