name: "deps(precommit): bump all dependencies"
#pipelineid: percommit/autodiscovery
automerge: false
labels:
  - dependencies

scm:
  enabled: false
  user: updatecli-bot
  #email: updatecli-bot@updatecli.io
  #owner: updatecli
  #repository: "repository"
  #token: "xxx"
  username: "updatecli"
  branch: main
  # commitusingapi: false

# spec:
groupby: all
