pipelineid: golangci-lint
automerge: false
labels:
  - chore
  - dependencies

scm:
  enabled: false
  # kind defines the SCM kind to use for this policy
  # Accepted values: github, gitea, bitbucket, gitlab, stash
  kind: github
  # user: updatecli-bot
  # email: updatecli-bot@updatecli.io
  # owner: updatecli
  # repository: website
  ## env_token defines the environment variable to use to retrieve the token
  env_token: GITHUB_TOKEN
  # #token: "xxx"
  # username: "updatecli-bot"
  # branch: main

name: 'deps: Updatecli version used by GitHub action'

versionpattern: "*"

## The Github settings is used to retrieve the latest NodeJS version
github:
  #token: ""
  env_token: "GITHUB_TOKEN"
  #username: ""
  env_username: "GITHUB_ACTOR"