name: 'deps: Bump Golang version'
pipelineid: golang/version
automerge: false
labels:
  - dependencies

scm:
  enabled: false
  # user: updatecli-bot
  # email: updatecli-bot@updatecli.io
  # owner: updatecli
  # repository: updatecli
  # token: "xxx"
  # username: "updatecli-bot"
  # branch: main

