---
# Helpers
# {{ $GitHubUser := env "GITHUB_ACTOR"}}
# {{ $GitHubRepositoryList := env "GITHUB_REPOSITORY" | split "/"}}
# {{ $GitHubPAT := env "GITHUB_TOKEN"}}
# {{ $GitHubUsername := env "GITHUB_ACTOR"}}}

name : '{{ .name }}'
pipelineid: '{{ .pipelineid }}'

# Only enable the scm section if Updatecli is executed from a Github Action
# {{ if or (.scm.enabled) (env "GITHUB_REPOSITORY") }}
actions:
    default:
        title: 'deps: bump golangci-lint to {{ source "golangci-lint" }}'
        kind: "github/pullrequest"
        spec:
            automerge: {{ .automerge }}
            labels:
                - "chore"
                - "dependencies"
            mergemethod: "squash"
        scmid: "default"

scms:
    default:
        kind: "github"
        spec:
            # Priority set to the environment variable
            user: '{{ default $GitHubUser .scm.user }}'
            email: '{{ .scm.email }}'
            owner: '{{ default $GitHubRepositoryList._0 .scm.owner }}'
            repository: '{{ default $GitHubRepositoryList._1 .scm.repository }}'
            token: '{{ default $GitHubPAT .scm.token }}'
            username: '{{ default $GitHubUsername .scm.username }}'
            branch: '{{ .scm.branch }}'
#{{ if .scm.commitusingapi }}
      commitusingapi: {{ .scm.commitusingapi }}
# {{ end }}
# {{ end }}

sources:
    golangci-lint:
        name: "Get latest Updatecli version"
        kind: "githubrelease"
        spec:
            owner: "golangci"
            repository: "golangci-lint"
            token: '{{ default .scm.token $GitHubPAT }}'
            username: '{{ default .scm.username $GitHubUsername }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'

targets:
    githubaction:
        name: 'deps: bump golangci-lint in GitHub Action to {{ source "golangci-lint" }}'
        kind: yaml
        spec:
            engine: yamlpath 
            key: '$.jobs.*.steps[?(@.uses =~ /^golangci\/golangci-lint-action/)].with.version'
            files:
             - '.github/workflows/*'
            searchpattern: true
# Only enable the scm section if Updatecli is executed from a Github Action
# {{ if or (.scm.enabled) (env "GITHUB_REPOSITORY") }}
        scmid: default
# {{ end }}

# Represent the minimum version of Updatecli required to run this policy
version: v0.68.0
