name : '{{ .name }}'
pipelineid: '{{ .pipelineid }}'
version: "v0.103.0"

sources:
    golangci-lint:
        name: "Get latest Updatecli version"
        kind: "githubrelease"
        spec:
            owner: "golangci"
            repository: "golangci-lint"
            token: '{{ default ( env .github.env_token ) .github.token }}'
            username: '{{ default ( env .github.env_username ) .github.username }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'

targets:
    githubaction:
        name: 'deps: bump golangci-lint in GitHub Action to {{ source "golangci-lint" }}'
        kind: yaml
        spec:
            engine: yamlpath 
            key: '$.jobs.*.steps[?(@.uses =~ /^golangci\/golangci-lint-action/)].with.version'
            files:
             - '.github/workflows/*'
            searchpattern: true
# {{ if .scm.enabled }}
        scmid: default
# {{ end }}