name: "deps(prow): bump all dependencies"
#pipelineid: prow/autodiscovery
automerge: false

scm:
  enabled: false
  user: updatecli-bot
  #email: updatecli-bot@updatecli.io
  #owner: updatecli
  #repository: "repository"
  #token: "xxx"
  username: "updatecli-bot"
  branch: main
  # commitusingapi: false

# spec:
groupby: all

