name : 'deps: Bump Node version in Netlify configuration'
pipelineid: '{{ .pipelineid }}'

sources:
    majornodeversion:
        name: "Get latest NodeJS version"
        kind: "githubrelease"
        transformers:
            - trimprefix: v
            - findsubmatch:
                pattern: ^(\d*)
                captureindex: 0
        spec:
            owner: "nodejs"
            repository: "node"
            token: '{{ default ( env .github.env_token ) .github.token }}'
            username: '{{ default ( env .github.env_username ) .github.username }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'
    node:
        name: "Get latest NodeJS version"
        kind: "githubrelease"
        spec:
            owner: "nodejs"
            repository: "node"
            token: '{{ default ( env .github.env_token ) .github.token }}'
            username: '{{ default ( env .github.env_username ) .github.username }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'
        transformers:
            - trimprefix: v
targets:
    netlify:
        name: 'deps: update Node used by Netlify to {{ source "node" }}'
        kind: file
        disablesourceinput: true
        spec:
            file: netlify.toml
            matchpattern: NODE_VERSION = "(.*)"
            replacepattern: NODE_VERSION = "{{ source "node" }}"
# {{ if .scm.enabled}}
        scmid: default
# {{ end }}
