name: 'deps(golang): Bump all dependencies'
pipelineid: golang/autodiscovery/all
automerge: false
labels:
  - dependencies

scm:
  enabled: false
  # kind defines the SCM kind to use for this policy
  # Accepted values: github, gitea, bitbucket, gitlab, stash
  kind: github
  # user: updatecli-bot
  # email: updatecli-bot@updatecli.io
  # owner: updatecli
  # repository: updatecli
  # token: "xxx"
  ## env_token defines the environment variable to use to retrieve the token
  env_token: GITHUB_TOKEN
  # username: "updatecli-bot"
  # branch: main
  ## commitusingapi defines if the commit should be done using the GitHub API
  ## Only compatible with GitHub 
  # commitusingapi: false

# spec:
groupby: all
