---
# Helpers
# {{ $GitHubUser := env "GITHUB_ACTOR"}}
# {{ $GitHubPAT := env "GITHUB_TOKEN" }}
# {{ $GitHubRepositoryList := env "GITHUB_REPOSITORY" | split "/"}}
# {{ $GitHubUsername := env "GITHUB_ACTOR" }}

name : 'deps: Bump NPM version in Netlify configuration'
pipelineid: '{{ .pipelineid }}'

# Only enable the scm section if Updatecli is executed from a Github Action
# {{ if or (.scm.enabled) (env "GITHUB_REPOSITORY") }}
actions:
    default:
        kind: "github/pullrequest"
        spec:
            automerge: {{ .automerge }}
# {{ if .labels }}
            labels:
# {{ range .labels }}
                - {{ . }}
# {{ end }}
# {{ end }}
            mergemethod: "squash"
        scmid: "default"

scms:
    default:
        kind: "github"
        spec:
            # Priority set to the environment variable
            user: '{{ default $GitHubUser .scm.user }}'
# {{ if .scm.email }}
            email: '{{ .scm.email }}'
# {{ end }}
            owner: '{{ default $GitHubRepositoryList._0 .scm.owner }}'
            repository: '{{ default $GitHubRepositoryList._1 .scm.repository }}'
            token: '{{ default $GitHubPAT .scm.token }}'
            username: '{{ default $GitHubUsername .scm.username }}'
            branch: '{{ .scm.branch }}'
#{{ if .scm.commitusingapi }}
            commitusingapi: {{ .scm.commitusingapi }}
# {{ end }}
# {{ end }}

sources:
    npm:
        name: "Get latest NPM version"
        kind: "githubrelease"
        spec:
            owner: "npm"
            repository: "cli"
            token: '{{ default .scm.token $GitHubPAT }}'
            username: '{{ default .scm.username $GitHubUsername }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'
        transformers:
            - trimprefix: v
targets:
    netlify:
        name: 'deps: update NPM used by Netlify to {{ source "npm" }}'
        kind: file
        disablesourceinput: true
        spec:
            file: netlify.toml
            matchpattern: NPM_VERSION = "(.*)"
            replacepattern: NPM_VERSION = "{{ source "npm" }}"
# Only enable the scm section if Updatecli is executed from a Github Action
# {{ if or (.scm.enabled) (env "GITHUB_REPOSITORY") }}
        scmid: default
# {{ end }}

