name : 'deps: Bump NPM version in Netlify configuration'
pipelineid: '{{ .pipelineid }}'
version: v0.103.0

sources:
    npm:
        name: "Get latest NPM version"
        kind: "githubrelease"
        spec:
            owner: "npm"
            repository: "cli"
            token: '{{ default ( env .github.env_token ) .github.token }}'
            username: '{{ default ( env .github.env_username ) .github.username }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'
        transformers:
            - trimprefix: v
targets:
    netlify:
        name: 'deps: update NPM used by Netlify to {{ source "npm" }}'
        kind: file
        disablesourceinput: true
        spec:
            file: netlify.toml
            matchpattern: NPM_VERSION = "(.*)"
            replacepattern: NPM_VERSION = "{{ source "npm" }}"
# {{ if .scm.enabled }}
        scmid: default
# {{ end }}

