---
# Helpers
# {{ $GitHubUser := env "GITHUB_ACTOR"}}
# {{ $GitHubPAT := env "GITHUB_TOKEN" }}
# {{ $GitHubRepositoryList := env "GITHUB_REPOSITORY" | split "/"}}
# {{ $GitHubUsername := env "GITHUB_ACTOR" }}
# {{ $GitHubBranch := env "GITHUB_REF_NAME" }}

name : 'deps: Bump HUGO version in Netlify configuration'
pipelineid: '{{ .pipelineid }}'

# Only enable the scm section if Updatecli is executed from a Github Action
# {{ if or (.scm.enabled) (env "GITHUB_REPOSITORY") }}
actions:
    default:
        title: 'deps: bump HUGO to {{ source "hugo" }}'
        kind: "github/pullrequest"
        spec:
            automerge: {{ .automerge }}
            labels:
                - "chore"
                - "dependencies"
            mergemethod: "squash"
        scmid: "default"
# {{ end }}

scms:
# Only enable the scm section if Updatecli is executed from a Github Action
# {{ if or (.scm.enabled) (env "GITHUB_REPOSITORY") }}
    default:
        kind: "github"
        spec:
            # Priority set to the environment variable
            user: '{{ default .scm.user $GitHubUser}}'
            email: '{{ .scm.email }}' 
            owner: '{{ default .scm.owner $GitHubRepositoryList._0 }}' 
            repository: '{{ default .scm.repository $GitHubRepositoryList._1 }}' 
            token: '{{ default .scm.token $GitHubPAT }}' 
            username: '{{ default .scm.username $GitHubUsername }}' 
            branch: '{{ default .scm.branch $GitHubBranch }}' 
# {{ end }}

sources:
    hugo:
        name: "Get latest hugo version"
        kind: "githubrelease"
        spec:
            owner: "gohugoio"
            repository: "hugo"
            token: '{{ default .scm.token $GitHubPAT }}' 
            username: '{{ default .scm.username $GitHubUsername }}' 
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'
        transformers:
            - trimprefix: v
targets:
    netlify:
        name: 'deps: update hugo used by Netlify to {{ source "hugo" }}'
        kind: file
        disablesourceinput: true
        spec:
            file: netlify.toml
            matchpattern: HUGO_VERSION = "(.*)"
            replacepattern: HUGO_VERSION = "{{ source "hugo" }}"
# Only enable the scm section if Updatecli is executed from a Github Action
# {{ if or (.scm.enabled) (env "GITHUB_REPOSITORY") }}
        scmid: default
# {{ end }}