name : 'deps: Bump HUGO version in Netlify configuration'
pipelineid: '{{ .pipelineid }}'
version: v0.103.0

sources:
    hugo:
        name: "Get latest hugo version"
        kind: "githubrelease"
        spec:
            owner: "gohugoio"
            repository: "hugo"
            token: '{{ default ( env .github.env_token ) .github.token }}'
            username: '{{ default ( env .github.env_username ) .github.username }}'
            versionfilter:
                kind: "semver"
                pattern: '{{ .versionpattern }}'
        transformers:
            - trimprefix: v
targets:
    netlify:
        name: 'deps: update hugo used by Netlify to {{ source "hugo" }}'
        kind: file
        disablesourceinput: true
        spec:
            file: netlify.toml
            matchpattern: HUGO_VERSION = "(.*)"
            replacepattern: HUGO_VERSION = "{{ source "hugo" }}"
# {{ if .scm.enabled }}
        scmid: default
# {{ end }}
