name: Validate Policies

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish
        run: make test

